### ISSUE TITLE
Enable Azure pipelines

### ISSUE THREAD

**Issue by jaraco** [jazzband/inflect#101]
Following the practices from my other projects, I'd like to enable this project for Azure pipelines and cut releases from tagged commits from there.

I've found that I'm unable to add a Pipeline for https://dev.azure.com/jaraco/inflect, so I've requested permission for that project to access the Jazzband organization for this purpose.

@jezdez If you would please approve that, it would enable seamless releases of tagged commits.

**Comment by jezdez** [comment]
Azure is not currently supported.

**Comment by jezdez** [comment]
To clarify, the reason Azure Pipelines is not supported since the only way that automated releases can be maintained in a sensible (bus factor > 1) and secure (release review by project leads) fashion is by using the Jazzband package index. Jazzband has settled on using Travis CI for this purpose and supporting a second CI service would be not possible. If you disagree I'm happy to transfer the project back to you.
