### ISSUE TITLE
Singular noun of specimen incorrectly converted to speciman

### ISSUE THREAD

**Issue by MaximMoinat** [jazzband/inflect#77]
An additional exception to the -men --> -man rule

**Comment by hugovk** [comment]
```python
Python 3.7.3 (default, Mar 27 2019, 09:23:15)
[Clang 10.0.1 (clang-1001.0.46.3)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import inflect
>>> p = inflect.engine()
>>> p.singular_noun("specimen")
'speciman'
>>> p.plural_noun("specimen")
'specimens'
>>>
```


> The method ``singular_noun()`` takes a *plural* English noun or
 pronoun and returns its singular. Pronouns in the nominative ("we" ->
 "I") and accusative ("us" -> "me") cases are handled, as are
 possessive pronouns ("ours" -> "mine"). When third person
 singular pronouns are returned they take the neuter gender by default
 ("they" -> "it"), not ("they"-> "she") nor ("they" -> "he"). This can be
 changed with ``gender()``.

https://github.com/jazzband/inflect#forming-plurals-and-singulars

The current behaviour is kind of by design; junk in, junk out: don't give singulars to `singular_noun()`.

**Comment by MaximMoinat** [comment]
Thanks for the answer, that's clear. Will close the issue.

Unfortunately in this case the application doesn't know whether the input is singular or plural. So another way of 'homogenising' everything to singular form has to be found.
